dist: trusty
language: nix
script:
- ls
- mkdir holochain-basic-chat
- shopt -s extglob
- mv !(holochain-basic-chat) holochain-basic-chat
- ls
- cd holochain-basic-chat
- cd ..
- ls
- git clone https://github.com/holochain/personas-profiles.git
- cd personas-profiles
- nix-shell --run 'npm run hc:build' https://holochain.love
- cd ..
- cd holochain-basic-chat
- nix-shell --run 'npm run hc:test' https://holochain.love
