dist: trusty
language: nix
script:
- git clone https://github.com/holochain/holochain-rust.git
- ls
- nix-shell --run 'hc-V && cd ui-src && npm install && cd .. && npm run prerelease' https://github.com/holochain/holochain-rust/archive/3b42375dc31442b62855cff8c339a6422c447176.tar.gz
- PACKAGE_NAME=$(node -p -e "require('./package.json').name")
- PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
- cd release/ui
- ls
- zip -r $PACKAGE_NAME-$PACKAGE_VERSION.zip *
- cd ..
deploy:
  provider: releases
  api-key:
    secure: hK5PuJtzxGoyRKxlIhSLzzrqpRsOcSP0e8Nr4t2ccL5P55FSSfCvwYMDo7wmJjQEBZUr73c/h7LtWq4OKoxVV3wAWudPgH7X/aQbHKxhH6fF2HoIYRdCc/6GxZrJ+z49jIu3rHBWhPtyfrUXG5wOEKiwdD42P9/uf4s5Pa8RdHPSSYofueiqZUff2whRrbh+Y98C0unJuwNIJW+pZSHSXZycCGBfL8Hotv7tFdPulsl+isZ3ib81KenRhwXvZod64rnIOR6KayvwVR56eqwkuiD3xH66MasBrNE5+idb8MYUJ/Xk8NmUwa1mbaGL3B4y8JSdEsgFcTWVjBaGaFSvBAC9ICwQpR4WW4WxCuu6jeAu9LRoH6kcD75QtcGpObYqcvKXoWPvbjfplcOdmWS3eVe+dysWDDFG/PUlooL76eNqqkYEq4O8UYZ0G9xWSX5LAjiSC08yliGbdhDK4uDmpddlDke5hEgXS8+EyY15vNTDvoNw9C1k37lDMepMj44LClRsH03gW8yHKSxbPfrQWDdPnBg5PlcOKUBfrsVng7g/IccXUIj2EqQf+zA0pcMwWv3bI0StzMlTFqVOYi/mDLWhrfQhol6VN2M8cHEfAt1Ud1WJOL5wumFCShMLETrQa9siEH2MXzPmD47debPa9JkS+aYAQfJ+Dn3ruyCG1Zs=
  file:
    - "ui/$PACKAGE_NAME-$PACKAGE_VERSION.zip"
    - "dna/holochain-basic-chat.dna.json"
  skip_cleanup: true
  on:
    tags: true
    branch: master
