# -----------  Agents  -----------

[[agents]]
id = "test_agent3"
name = "Agent 3"
public_address = "HcSciD4Rn7wc3hno39KxqMHKQBr5yegivdQq9BzsG5q54pf46NsyZc8Fp6dsper"
keystore_file = "./agent3.keystore"

# -----------  DNA  -----------

[[dnas]]
id = "personas_profiles"
file = "../personas-profiles/dna/personas-profiles-agent3.dna.json"
hash = "QmWMfiFWpGFeB44ij5DYPcedGkVXjU7qyp15yrXAGhy6Xy"

[[instances]]
id = "personas-profiles"
dna = "personas_profiles"
agent = "test_agent3"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[dnas]]
id = "chat_dna"
file = "./dna/holochain-basic-chat.dna.json"
hash = "QmQxk7VMC9EqUtVnkC3s5DUhHAWcXW6xKgqjtDXEVfFTgg"

[[instances]]
id = "holo-chat"
dna = "chat_dna"
agent = "test_agent3"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage-agent3"

[[bridges]]
caller_id = "holo-chat"
callee_id = "personas-profiles"
handle = "p-p-bridge"

[[interfaces]]
id = "chat_websocket_interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 3403
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "chat_http_interface"
[interfaces.driver]
type = "http"
port = 4403
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "p_p_websocket_interface"
[interfaces.driver]
type = "websocket"
port = 5403
[[interfaces.instances]]
id = "personas-profiles"

# -----------  UI  -----------

# [[ui_bundles]]
# id = "main"
# root_dir = "./ui"
# hash = "Qm000"
#
# [[ui_interfaces]]
# id = "ui-interface"
# bundle = "main"
# port = 3003
# dna_interface = "chat_websocket_interface"

[[ui_bundles]]
id = "persona_profiles_ui_bundle"
root_dir = "../personas-profiles/ui"
hash = "Qm000"

[[ui_interfaces]]
id = "persona_profiles_ui_interface"
bundle = "persona_profiles_ui_bundle"
port = 4003
dna_interface = "p_p_websocket_interface"

# -----------  Networking  -----------

[network]
type = "n3h"
n3h_mode = "REAL"
n3h_persistence_path = "./n3h-agent3"
n3h_log_level = "i"
bootstrap_nodes = []
