
[logger]
type = "debug"
[[logger.rules.rules]]
pattern = "^debug"

# -----------  Agents  -----------


[[agents]]
id = "test_agent1"
name = "HoloTester1"
public_address = "HcScJ9SbHkYqebavk3NvSHgYwa5vgcdz4p34V6R6rZdg4NimUhQN7i4Yo8awoqa"
key_file = "/Users/connor/Library/Preferences/org.holochain.holochain/keys/HcScJ9SbHkYqebavk3NvSHgYwa5vgcdz4p34V6R6rZdg4NimUhQN7i4Yo8awoqa"

# [[agents]]
# id = "test_agent2"
# name = "HoloTester2"
# public_address = "bagel-----------------------------------------------------------------------------AAADAq0mCu"
# key_file = "holo_tester.key"

# [[agents]]
# id = "test_agent3"
# name = "HoloTester3"
# public_address = "croissant-------------------------------------------------------------------------AAAEuHzxV4"
# key_file = "holo_tester.key"

# -----------  DNA  -----------


[[dnas]]
id = "chat_dna"
file = "dna/holo-chat.hcpkg"
hash = "Qm328wyq38924y"

[[instances]]
id = "holo-chat"
dna = "chat_dna"
agent = "test_agent1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3400
[[interfaces.instances]]
id = "holo-chat"

# -----------  UI  -----------

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3000
dna_interface = "websocket_interface"

# -----------  Networking  -----------

[network]
n3h_path = "/Users/connor/code/holochain/n3h"
n3h_log_level = "i"
n3h_persistence_path = "/tmp"
bootstrap_nodes = []


# -----------  Networking instructions  -----------

# To get networking running, check out https://hackmd.io/T04JyDBDR16JrltmFLtIoA?view
