# -----------  Agents  -----------

[[agents]]
id = "test_agent2"
name = "Agent 2"
public_address = "HcSCIUKodbWktcbmwyAaVrYnsbadi6b9sOV9D4ZoE8i333ZtcGw38Jn3U6u63qi"
keystore_file = "./agent2.keystore"

# -----------  DNA  -----------

[[dnas]]
id = "personas_profiles"
file = "../personas-profiles/dna/personas-profiles-agent2.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "personas-profiles"
dna = "personas_profiles"
agent = "test_agent2"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[dnas]]
id = "chat_dna"
file = "./dna/holochain-basic-chat.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "holo-chat"
dna = "chat_dna"
agent = "test_agent2"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage-agent2"

[[bridges]]
caller_id = "holo-chat"
callee_id = "personas-profiles"
handle = "p-p-bridge"

[[interfaces]]
id = "chat_websocket_interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 3402
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "chat_http_interface"
[interfaces.driver]
type = "http"
port = 4402
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "p_p_websocket_interface"
[interfaces.driver]
type = "websocket"
port = 5402
[[interfaces.instances]]
id = "personas-profiles"

# -----------  UI  -----------

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3002
dna_interface = "chat_websocket_interface"

[[ui_bundles]]
id = "persona_profiles_ui_bundle"
root_dir = "../personas-profiles/ui"
hash = "Qm000"

[[ui_interfaces]]
id = "persona_profiles_ui_interface"
bundle = "persona_profiles_ui_bundle"
port = 4002
dna_interface = "p_p_websocket_interface"

# -----------  Networking  -----------

[network]
n3h_mode = "REAL"
n3h_persistence_path = "/Users/philipbeadle/holochain/Holochain/n3h-agent2"
n3h_log_level = "i"
bootstrap_nodes = []
