# -----------  Agents  -----------


[[agents]]
id = "test_agent1"
name = "Agent 1"
public_address = "HcSCJbpm8CZparb6f5iEKKRv4Te4op93q6ESMRuDtwp9abbzV8zYTF7EKqqw9ei"
keystore_file = "./agent1.keystore"

# -----------  DNA  -----------

[[dnas]]
id = "personas_profiles"
file = "../personas-profiles/dna/personas-profiles-agent1.dna.json"
hash = "QmUaGUyu7dv1YcCAFDvacTHh9eeuK6mZnYgmBUSoyWB86R"


[[instances]]
id = "personas-profiles"
dna = "personas_profiles"
agent = "test_agent1"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[dnas]]
id = "chat_dna"
file = "./dna/holochain-basic-chat.dna.json"
hash = "QmbA6WyhkCGrorEWtKhQnsDgJhSopepNi1ViKx78PkCe3V"

[[instances]]
id = "holo-chat"
dna = "chat_dna"
agent = "test_agent1"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage-agent1"

[[bridges]]
caller_id = "holo-chat"
callee_id = "personas-profiles"
handle = "p-p-bridge"

[[interfaces]]
id = "chat_websocket_interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 3401
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "chat_http_interface"
[interfaces.driver]
type = "http"
port = 4401
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "p_p_websocket_interface"
[interfaces.driver]
type = "websocket"
port = 5401
[[interfaces.instances]]
id = "personas-profiles"

# -----------  UI  -----------

# [[ui_bundles]]
# id = "main"
# root_dir = "./ui"
# hash = "Qm000"
#
# [[ui_interfaces]]
# id = "ui-interface"
# bundle = "main"
# port = 3001
# dna_interface = "chat_websocket_interface"

# [[ui_bundles]]
# id = "persona_profiles_ui_bundle"
# root_dir = "../personas-profiles/ui"
# hash = "Qm000"
#
# [[ui_interfaces]]
# id = "persona_profiles_ui_interface"
# bundle = "persona_profiles_ui_bundle"
# port = 4001
# dna_interface = "p_p_websocket_interface"

# -----------  Networking  -----------

[network]
type = "n3h"
n3h_mode = "REAL"
n3h_persistence_path = "./n3h-agent1"
n3h_log_level = "i"
bootstrap_nodes = []
