# -----------  Agents  -----------

[[agents]]
id = "test_agent4"
name = "Agent 4"
public_address = "HcSCjhqYOqc7u3uwybCm3f8ze934wzQywhYfjnbyWfuyp6xnqk58VTbM5obhujr"
keystore_file = "./agent4.keystore"

# -----------  DNA  -----------

[[dnas]]
id = "personas_profiles"
file = "../personas-profiles/dna/personas-profiles-agent4.dna.json"
hash = "QmNMwZisbTiMrhdMPqXtWXTfjHHoNcq5DbfVBb4FZH4YWM"

[[instances]]
id = "personas-profiles"
dna = "personas_profiles"
agent = "test_agent4"
[instances.storage]
type = "memory"
path = "tmp-storage"

[[dnas]]
id = "chat_dna"
file = "./dna/holochain-basic-chat.dna.json"
hash = "QmQhANuLdNQvSLJ4gSaBMeqCZF7vsSTprcrwC9ddxHu1Lh"

[[instances]]
id = "holo-chat"
dna = "chat_dna"
agent = "test_agent4"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "memory"
path = "tmp-storage-agent4"

[[bridges]]
caller_id = "holo-chat"
callee_id = "personas-profiles"
handle = "p-p-bridge"

[[interfaces]]
id = "chat_websocket_interface"
admin = true
[interfaces.driver]
type = "websocket"
port = 3404
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "chat_http_interface"
[interfaces.driver]
type = "http"
port = 4404
[[interfaces.instances]]
id = "holo-chat"

[[interfaces]]
id = "p_p_websocket_interface"
[interfaces.driver]
type = "websocket"
port = 5404
[[interfaces.instances]]
id = "personas-profiles"

# -----------  UI  -----------

# [[ui_bundles]]
# id = "main"
# root_dir = "./ui"
# hash = "Qm000"
#
# [[ui_interfaces]]
# id = "ui-interface"
# bundle = "main"
# port = 3004
# dna_interface = "chat_websocket_interface"

[[ui_bundles]]
id = "persona_profiles_ui_bundle"
root_dir = "../personas-profiles/ui"
hash = "Qm000"

[[ui_interfaces]]
id = "persona_profiles_ui_interface"
bundle = "persona_profiles_ui_bundle"
port = 4004
dna_interface = "p_p_websocket_interface"

# -----------  Networking  -----------

[network]
type = "n3h"
n3h_mode = "REAL"
n3h_persistence_path = "./n3h-agent4"
n3h_log_level = "i"
bootstrap_nodes = []
