version: 2

jobs:
 build:
  macos:
   xcode: "9.3.0"
  steps:
   - checkout
   - run: brew install wget zmq
   - run: wget https://github.com/holochain/holochain-rust/releases/download/v0.0.4-alpha/conductor-v0.0.4-alpha-x86_64-apple-darwin.tar.gz
   - run: tar -xvf $HOME/project/conductor-v0.0.4-alpha-x86_64-apple-darwin.tar.gz
   - run: cp $HOME/project/conductor-v0.0.4-alpha-x86_64-apple-darwin/holochain $HOME/project/holochain
   # - run: . $HOME/project/run.sh
